### ISSUE TITLE
make maps proper with tiles

### ISSUE THREAD

**Issue by jbentke** [simon-jentzsch/nephis-world#1]
Die maps die gebaut wurden in tiles können nicht in phaser geladen werden

**Comment by MrCoax** [comment]
Wenn man das Tileset in Tiled geladen hat muss man unter der Tileset-Ablage auf den Knopf "Tileset Einbetten" drücken. Jetzt muss man in der .json nur noch das ".png" hinter dem Name im Feld"name" hinzufügen.
